### ISSUE TITLE
SENSE

### ISSUE THREAD

**Issue by Leuzeas** [madman-bob/fitbit-reader#2]
I warmly welcome! :-)

Is there any way to install this app on Fitbit SENSE?

I will be very grateful for Your answer and possible help in implementing Reader on SENSE.

Thanks in advance!  :-)

I warmly serve you,
Leuzeas

**Comment by madman-bob** [comment]
This project is unsupported, and as such is not available on the app store for more recent devices.

That said, I see no technical reasons this app would not work on more recent devices. If you are able, you could download the source code, and [manually build and install](https://dev.fitbit.com/getting-started/) the app yourself.
